// Generated by Quicktype.io
import 'package:easingles/Models/Messages.dart';
import 'package:easingles/Models/Photos.dart';

class Login {
  int id;
  String phoneNumber;
  String password;
  String token;
  String refreshToken;
  DateTime created;
  User login;

  Login({
    required this.id,
    required this.phoneNumber,
    required this.password,
    required this.token,
    required this.refreshToken,
    required this.created,
    required this.login,
  });

  factory Login.fromJson(Map<String, dynamic> json) => Login(
        id: json["id"],
        phoneNumber: json["phoneNumber"],
        password: json["password"],
        token: json["token"],
        refreshToken: json["refreshToken"],
        created: DateTime.parse(json["created"]),
        login: User.fromJson(json["login"]),
      );

  Map<String, dynamic> toJson() => {
        "id": id,
        "phoneNumber": phoneNumber,
        "password": password,
        "token": token,
        "refreshToken": refreshToken,
        "created": created.toIso8601String(),
        "login": login.toJson(),
      };
}

class User {
  int id;
  String firstName;
  String lastName;
  String? day;
  String? month;
  String? year;
  String? country;
  String? district;
  String? village;
  String? profilepic;
  bool online =false;
  String? gender;
  String? hopes;
  String? religion;
  String? imgx;
  String? imgxx;
  String? imgxxx;
  String? imgxxxx;
  List<Liked> liked;
  String? referalCode;
  Login login;
  int loginId;
  List<Conversation> conversations =[];
  List<Photo> photos;
  String? contact;
  String? twitter;
  String? instagram;
  String? facebook;
  String? email;
  String? about;
  bool promoted;
  DateTime subscription;
  DateTime endsubscription;
  int totalshows =0;
  String? promoterurl;

  User({
    required this.id,
    required this.firstName,
    required this.lastName,
    this.day,
    this.month,
    this.year,
    this.country,
    this.district,
    this.village,
    this.profilepic,
    required this.online,
    this.gender,
    this.hopes,
    this.religion,
    this.imgx,
    this.imgxx,
    this.imgxxx,
    this.imgxxxx,
    required this.liked,
    this.referalCode,
    required this.login,
    required this.loginId,
    required this.conversations,
    required this.photos,
    this.contact,
    this.twitter,
    this.instagram,
    this.facebook,
    this.email,
    this.about,
    required this.promoted,
    required this.subscription,
    required this.endsubscription,
    required this.totalshows,
    this.promoterurl,
  });

  factory User.fromJson(Map<String, dynamic> json) => User(
        id: json["id"],
        firstName: json["firstName"],
        lastName: json["lastName"],
        day: json["day"],
        month: json["month"],
        year: json["year"],
        country: json["country"],
        district: json["district"],
        village: json["village"],
        profilepic: json["profilepic"],
        online: json["online"],
        gender: json["gender"],
        hopes: json["hopes"],
        religion: json["religion"],
        imgx: json["imgx"],
        imgxx: json["imgxx"],
        imgxxx: json["imgxxx"],
        imgxxxx: json["imgxxxx"],
        liked: List<Liked>.from(json["liked"].map((x) => Liked.fromJson(x))),
        referalCode: json["referalCode"],
        login: Login.fromJson(json["login"]),
        loginId: json["loginId"],
        conversations: List<Conversation>.from(
            json["conversations"].map((x) => Conversation.fromJson(x))),
        photos: List<Photo>.from(json["photos"].map((x) => Photo.fromJson(x))),
        contact: json["contact"],
        twitter: json["twitter"],
        instagram: json["instagram"],
        facebook: json["facebook"],
        email: json["email"],
        about: json["about"],
        promoted: json["promoted"],
        subscription: json["subscription"] != null ? DateTime.parse(json["subscription"]) : DateTime.now(),
        endsubscription: json["endsubscription"] != null ? DateTime.parse(json["endsubscription"]) : DateTime.now(),
        totalshows: json["totalshows"],
        promoterurl: json["promoterurl"],
      );

  Map<String, dynamic> toJson() => {
        "id": id,
        "firstName": firstName,
        "lastName": lastName,
        "day": day,
        "month": month,
        "year": year,
        "country": country,
        "district": district,
        "village": village,
        "profilepic": profilepic,
        "online": online,
        "gender": gender,
        "hopes": hopes,
        "religion": religion,
        "imgx": imgx,
        "imgxx": imgxx,
        "imgxxx": imgxxx,
        "imgxxxx": imgxxxx,
        "liked": List<dynamic>.from(liked.map((x) => x.toJson())),
        "referalCode": referalCode,
        "login": login.toJson(),
        "loginId": loginId,
        "conversations":
            List<dynamic>.from(conversations.map((x) => x.toJson())),
        "photos": List<dynamic>.from(photos.map((x) => x.toJson())),
        "contact": contact,
        "twitter": twitter,
        "instagram": instagram,
        "facebook": facebook,
        "email": email,
        "about": about,
        "promoted": promoted,
        "subscription": subscription.toIso8601String(),
        "endsubscription": endsubscription.toIso8601String(),
        "totalshows": totalshows,
        "promoterurl": promoterurl,
      };
}

class Liked {
  int id;
  int likedUserId;
  User liked;
  int likeIded;

  Liked({
    required this.id,
    required this.likedUserId,
    required this.liked,
    required this.likeIded,
  });

  factory Liked.fromJson(Map<String, dynamic> json) => Liked(
        id: json["id"],
        likedUserId: json["likedUserId"],
        liked: User.fromJson(json["liked"]),
        likeIded: json["likeIded"],
      );

  Map<String, dynamic> toJson() => {
        "id": id,
        "likedUserId": likedUserId,
        "liked": liked.toJson(),
        "likeIded": likeIded,
      };
}

class Conversation {
  int id;
  List<User> chatUser;
  DateTime createdAt;
  List<Message> messages;

  Conversation({
    required this.id,
    required this.chatUser,
    required this.createdAt,
    required this.messages,
  });

  factory Conversation.fromJson(Map<String, dynamic> json) => Conversation(
        id: json["id"],
        chatUser: List<User>.from(json["chatUser"].map((x) => User.fromJson(x))),
        createdAt: DateTime.parse(json["createdAt"]),
        messages: List<Message>.from(json["messages"].map((x) => Message.fromJson(x))),
      );

  Map<String, dynamic> toJson() => {
        "id": id,
        "chatUser": List<dynamic>.from(chatUser.map((x) => x.toJson())),
        "createdAt": createdAt.toIso8601String(),
        "messages": List<dynamic>.from(messages.map((x) => x.toJson())),
      };
}

