// Generated by Quicktype.io

class Matches {
  int id;
  int matcher;
  int matched;
  bool seenI;
  bool seenx;

  Matches({
    required this.id,
    required this.matcher,
    required this.matched,
    required this.seenI,
    required this.seenx,
  });

  factory Matches.fromJson(Map<String, dynamic> json) => Matches(
        id: json["id"],
        matcher: json["matcher"],
        matched: json["matched"],
        seenI: json["seenI"],
        seenx: json["seenx"],
      );

  Map<String, dynamic> toJson() => {
        "id": id,
        "matcher": matcher,
        "matched": matched,
        "seenI": seenI,
        "seenx": seenx,
      };
}

class Moment {
  int id;
  int likes;
  List<Comments> comments;
  int owenId;
  String? hashTag;
  String? tagLine;
  String? imageOne;
  String? imageTwo;
  String? imageThree;
  String firstName;
  String lastName;
  DateTime date;

  Moment({
    required this.id,
    required this.likes,
    required this.comments,
    required this.owenId,
    required this.hashTag,
    required this.tagLine,
    required this.imageOne,
    required this.imageTwo,
    required this.imageThree,
    required this.firstName,
    required this.lastName,
    required this.date,
  });

  factory Moment.fromJson(Map<String, dynamic> json) => Moment(
        id: json["id"],
        likes: json["likes"],
        comments: List<Comments>.from(json["comments"].map((x) => Comments.fromJson(x))),
        owenId: json["owenId"],
        hashTag: json["hashTag"],
        tagLine: json["tagLine"],
        imageOne: json["imageOne"],
        imageTwo: json["imageTwo"],
        imageThree: json["imageThree"],
        firstName: json["firstName"],
        lastName: json["lastName"],
        date: DateTime.parse(json["date"]),
      );

  Map<String, dynamic> toJson() => {
        "id": id,
        "likes": likes,
        "comments": List<dynamic>.from(comments.map((x) => x.toJson())),
        "owenId": owenId,
        "hashTag": hashTag,
        "tagLine": tagLine,
        "imageOne": imageOne,
        "imageTwo": imageTwo,
        "imageThree": imageThree,
        "firstName": firstName,
        "lastName": lastName,
        "date": date.toIso8601String(),
      };
}

class Comments {
  int id;
  Moment? moment;
  int? momentId;
  String names;
  String df;
  String imageOne;
  DateTime date;

  Comments({
    required this.id,
    required this.moment,
    required this.momentId,
    required this.names,
    required this.df,
    required this.imageOne,
    required this.date,
  });

  factory Comments.fromJson(Map<String, dynamic> json) => Comments(
        id: json["id"],
        moment: json["moment"] != null ? Moment.fromJson(json["moment"]) : null,
        momentId: json["momentId"],
        names: json["names"],
        df: json["df"],
        imageOne: json["imageOne"],
        date: DateTime.parse(json["date"]),
      );

  Map<String, dynamic> toJson() => {
        "id": id,
        "moment": moment?.toJson(),
        "momentId": momentId,
        "names": names,
        "df": df,
        "imageOne": imageOne,
        "date": date.toIso8601String(),
      };
}

class Gifts {
  int id;
  int giftId;
  int value;
  int quantity;
  String name;
  String image;
  int owner;

  Gifts({
    required this.id,
    required this.giftId,
    required this.value,
    required this.quantity,
    required this.name,
    required this.image,
    required this.owner,
  });

  factory Gifts.fromJson(Map<String, dynamic> json) => Gifts(
        id: json["id"],
        giftId: json["giftId"],
        value: json["value"],
        quantity: json["quantity"],
        name: json["name"],
        image: json["image"],
        owner: json["owner"],
      );

  Map<String, dynamic> toJson() => {
        "id": id,
        "giftId": giftId,
        "value": value,
        "quantity": quantity,
        "name": name,
        "image": image,
        "owner": owner,
      };
}

class Transaction {
  int id;
  int amount;
  int ownerId;
  String reason;
  int? quantity;
  DateTime date;
  bool fulfilled;

  Transaction({
    required this.id,
    required this.amount,
    required this.ownerId,
    required this.reason,
    required this.quantity,
    required this.date,
    required this.fulfilled,
  });

  factory Transaction.fromJson(Map<String, dynamic> json) => Transaction(
        id: json["id"],
        amount: json["amount"],
        ownerId: json["ownerId"],
        reason: json["reason"],
        quantity: json["quantity"],
        date: DateTime.parse(json["date"]),
        fulfilled: json["fulfilled"],
      );

  Map<String, dynamic> toJson() => {
        "id": id,
        "amount": amount,
        "ownerId": ownerId,
        "reason": reason,
        "quantity": quantity,
        "date": date.toIso8601String(),
        "fulfilled": fulfilled,
      };
}

class Withdrawing {
  int id;
  int amount;
  bool approved;
  int userId;
  int quantity;
  String mobileNumber;
  DateTime date;
  String transactionId;

  Withdrawing({
    required this.id,
    required this.amount,
    required this.approved,
    required this.userId,
    required this.quantity,
    required this.mobileNumber,
    required this.date,
    required this.transactionId,
  });

  factory Withdrawing.fromJson(Map<String, dynamic> json) => Withdrawing(
        id: json["id"],
        amount: json["amount"],
        approved: json["approved"],
        userId: json["userId"],
        quantity: json["quantity"],
        mobileNumber: json["mobileNumber"],
        date: DateTime.parse(json["date"]),
        transactionId: json["transactionId"],
      );

  Map<String, dynamic> toJson() => {
        "id": id,
        "amount": amount,
        "approved": approved,
        "userId": userId,
        "quantity": quantity,
        "mobileNumber": mobileNumber,
        "date": date.toIso8601String(),
        "transactionId": transactionId,
      };
}
