// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPlaceholder_Replace_With_Your_Web_API_Key',
    appId: '1:Placeholder:web:Replace_With_Your_Web_App_ID',
    messagingSenderId: 'Placeholder',
    projectId: 'twinbrook-12f84',
    authDomain: 'twinbrook-12f84.firebaseapp.com',
    storageBucket: 'twinbrook-12f84.appspot.com',
    measurementId: 'G-PLACEHOLDER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPlaceholder_Replace_With_Your_Android_API_Key',
    appId: '1:Placeholder:android:Replace_With_Your_Android_App_ID',
    messagingSenderId: 'Placeholder',
    projectId: 'twinbrook-12f84',
    storageBucket: 'twinbrook-12f84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPlaceholder_Replace_With_Your_iOS_API_Key',
    appId: '1:Placeholder:ios:Replace_With_Your_iOS_App_ID',
    messagingSenderId: 'Placeholder',
    projectId: 'twinbrook-12f84',
    storageBucket: 'twinbrook-12f84.appspot.com',
    iosClientId: 'Placeholder-iOS-Client-ID',
    iosBundleId: 'com.yodate.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPlaceholder_Replace_With_Your_macOS_API_Key',
    appId: '1:Placeholder:macos:Replace_With_Your_macOS_App_ID',
    messagingSenderId: 'Placeholder',
    projectId: 'twinbrook-12f84',
    storageBucket: 'twinbrook-12f84.appspot.com',
    iosClientId: 'Placeholder-macOS-Client-ID',
    iosBundleId: 'com.yodate.com',
  );
}